<?php
$mailto="yogigambhir@yahoo.com";
$subject="Request for Quotation";
$thankyou="thanks.php";
$quotation = $_POST[quotation];
$code = $_POST[code];
$requirement = $_POST[details];
$name = $_POST[name];
$email = $_POST[email];
$phone = $_POST[phone];
$organization = $_POST[organization];
$address = $_POST[address];
$city = $_POST[city];
$pin = $_POST[pin];
$country = $_POST[country];
$remarks = $_POST[remarks];
$body.="-------------------------------------\n";
$body.="Product Code: $code\n";
$body.="Product Name: $quotation\n";
$body.="Details of Requirements: $requirement\n\n";
$body.="Visitor's Details:\n\n";
$body.="Name: $name\n";
$body.="E-mail: $email\n";
$body.="Phone: $phone\n";
$body.="Organization: $organization\n";
$body.="Address: $adress\n";
$body.="City/State: $city\n";
$body.="PIN/ZIP: $pin\n";
$body.="Country: $country\n";
$body.="Remarks / Feedback: $remarks\n";
$body.="-------------------------------------\n";
mail($mailto,$subject,$body,"From: $email\n");
Header ("Location: $thankyou");
?>